import Foundation

/// Local chat message model with streaming and tool event state.
struct ChatMessage: Identifiable {
    let id: String
    let role: Role
    let timestamp: Date
    var content: String
    var isStreaming: Bool
    var toolEvents: [ToolEvent]
    var attachedFiles: [AttachedFile]

    enum Role: String, Sendable {
        case user, assistant, system
    }

    init(
        id: String = UUID().uuidString,
        role: Role,
        content: String,
        timestamp: Date = .now,
        isStreaming: Bool = false,
        toolEvents: [ToolEvent] = [],
        attachedFiles: [AttachedFile] = []
    ) {
        self.id = id
        self.role = role
        self.content = content
        self.timestamp = timestamp
        self.isStreaming = isStreaming
        self.toolEvents = toolEvents
        self.attachedFiles = attachedFiles
    }

    /// True when message was auto-generated for file-only sends (no user text).
    var isFileOnlyMessage: Bool {
        !attachedFiles.isEmpty && content.isEmpty
    }
}

/// A file attached to or generated by a message.
struct AttachedFile: Identifiable, Sendable {
    let id: String
    let name: String
    let url: String?
    let type: FileType
    let thumbnail: Data?

    enum FileType: String, Sendable {
        case image, audio, video, file
    }

    init(id: String, name: String, url: String?, type: FileType, thumbnail: Data? = nil) {
        self.id = id
        self.name = name
        self.url = url
        self.type = type
        self.thumbnail = thumbnail
    }
}

/// Transcript message from /api/history.
struct TranscriptMessage: Codable, Sendable {
    let type: String
    let role: String
    let content: String
    let ts: Double

    var date: Date { Date(timeIntervalSince1970: ts / 1000) }
}

struct HistoryResponse: Codable, Sendable {
    let messages: [TranscriptMessage]
    let total: Int
}
